/**
 * Admin app labels (en + fa). A compact, self-contained bilingual map — the admin app does
 * not copy the merchant app's large i18n catalog; it ships only the labels it needs.
 * `fa` must contain every `en` key (enforced by the `Record<LabelKey, string>` type).
 */
export const en = {
  'app.name': 'WordPress Commerce OS Admin',
  'app.tagline': 'Internal platform operations',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong.',
  'common.retry': 'Retry',
  'common.back': 'Back',
  'common.mock': 'Mock',
  'common.all': 'All',
  'common.none': '—',
  'common.localeToggle': 'EN',
  'nav.overview': 'Overview',
  'nav.workflows': 'Workflows',

  // Platform overview
  'platformAdmin.title': 'Platform Admin',
  'platformAdmin.subtitle': 'Manage our SaaS customers, their stores, and platform health.',
  'platformAdmin.security.note':
    'Internal control layer — mock-only. No real billing, backend, secrets, or customer PII. Strict RBAC required before real data.',
  'platformAdmin.kpi.customers': 'Customers',
  'platformAdmin.kpi.activeSites': 'Active sites',
  'platformAdmin.kpi.mrr': 'MRR (mock)',
  'platformAdmin.kpi.openSupport': 'Open support',
  'platformAdmin.kpi.syncIssues': 'Sync issues',
  'platformAdmin.kpi.securityAlerts': 'Security alerts',
  'platformAdmin.section.atRisk': 'Customer health',
  'platformAdmin.section.sitesHealth': 'Site & sync health',
  'platformAdmin.section.subscriptions': 'Subscription health',
  'platformAdmin.section.support': 'Support operations',
  'platformAdmin.section.security': 'Recent security & audit',
  'platformAdmin.section.usage': 'Usage & limits',
  'platformAdmin.section.tasks': 'Next admin tasks',
  'platformAdmin.filter.atRisk': 'At risk',
  'platformAdmin.filter.pastDue': 'Past due',
  'platformAdmin.empty.tenants': 'No customers match this filter.',
  'platformAdmin.empty.signals': 'No security signals.',
  'platformAdmin.empty.tasks': 'No open admin tasks.',
  'platformAdmin.empty.sites': 'No sites to show.',
  'platformAdmin.tenant.sitesLabel': 'sites',
  'platformAdmin.tenant.lastActive': 'Last active',
  'platformAdmin.viewCustomer': 'Open',
  'platformAdmin.owner': 'Owner',
  'platformAdmin.plan': 'Plan',
  'platformAdmin.renews': 'Renews',
  'platformAdmin.trialEnds': 'Trial ends',
  'platformAdmin.health': 'Health',
  'platformAdmin.mrr': 'MRR (mock)',
  'platformAdmin.detail.profile': 'Customer profile',
  'platformAdmin.detail.subscription': 'Subscription',
  'platformAdmin.detail.sites': 'Sites & sync health',
  'platformAdmin.detail.tasks': 'Support & admin tasks',
  'platformAdmin.detail.security': 'Security & audit signals',
  'platformAdmin.detail.usage': 'Usage & limits',
  'platformAdmin.detail.notes': 'Internal notes',
  'platformAdmin.detail.notesPlaceholder': 'Internal notes will live here once the backend lands.',
  'platformAdmin.detail.back': 'Back to overview',
  'platformAdmin.notFound.title': 'Customer not found',
  'platformAdmin.notFound.body': 'This customer/tenant does not exist or is no longer available.',
  'platformAdmin.action.openSupport': 'Open support case',
  'platformAdmin.action.requestUpgrade': 'Request upgrade',
  'platformAdmin.action.reviewSync': 'Review sync issue',
  'platformAdmin.action.contactLater': 'Contact customer',
  'platformAdmin.action.suspendLater': 'Suspend',
  'platformAdmin.site.woo': 'WooCommerce',
  'platformAdmin.site.wooActive': 'WooCommerce active',
  'platformAdmin.site.wooMissing': 'WooCommerce missing',
  'platformAdmin.site.plugin': 'Plugin',
  'platformAdmin.site.lastSync': 'Last sync',
  'platformAdmin.site.queued': 'Queued',
  'platformAdmin.site.failures': 'Failures',
  'platformAdmin.site.signed': 'Signed sync',
  'platformAdmin.usage.orders': 'Orders synced',
  'platformAdmin.usage.events': 'Events captured',
  'platformAdmin.usage.api': 'API calls',
  'platformAdmin.usage.sites': 'Sites',
  'platformAdmin.usage.nearLimit': 'Near limit',
  'platformAdmin.task.next': 'Next',
  'platformAdmin.task.blocked': 'Blocked',

  // Status maps
  'platformAdmin.tenantStatus.active': 'Active',
  'platformAdmin.tenantStatus.trialing': 'Trialing',
  'platformAdmin.tenantStatus.past_due': 'Past due',
  'platformAdmin.tenantStatus.canceled': 'Canceled',
  'platformAdmin.tenantStatus.suspended': 'Suspended',
  'platformAdmin.subState.trialing': 'Trialing',
  'platformAdmin.subState.active': 'Active',
  'platformAdmin.subState.past_due': 'Past due',
  'platformAdmin.subState.canceled': 'Canceled',
  'platformAdmin.connection.connected': 'Connected',
  'platformAdmin.connection.pending': 'Pending',
  'platformAdmin.connection.disconnected': 'Disconnected',
  'platformAdmin.connection.error': 'Error',
  'platformAdmin.sync.healthy': 'Healthy',
  'platformAdmin.sync.delayed': 'Delayed',
  'platformAdmin.sync.stalled': 'Stalled',
  'platformAdmin.sync.never': 'Never synced',
  'platformAdmin.signed.verified': 'Signed: verified',
  'platformAdmin.signed.unsigned': 'Signed: unsigned',
  'platformAdmin.signed.invalid': 'Signed: invalid',
  'platformAdmin.signed.disabled': 'Signed: disabled',
  'platformAdmin.severity.info': 'Info',
  'platformAdmin.severity.warning': 'Warning',
  'platformAdmin.severity.critical': 'Critical',
  'platformAdmin.secType.raw_secret_rejected': 'Raw secret rejected',
  'platformAdmin.secType.invalid_signature': 'Invalid signature',
  'platformAdmin.secType.replay_rejected': 'Replay rejected',
  'platformAdmin.secType.permission_denied': 'Permission denied',
  'platformAdmin.secType.sync_validation_failed': 'Sync validation failed',
  'platformAdmin.secType.webhook_rejected': 'Webhook rejected',
  'platformAdmin.secType.audit_event': 'Audit event',
  'platformAdmin.priority.low': 'Low',
  'platformAdmin.priority.medium': 'Medium',
  'platformAdmin.priority.high': 'High',
  'platformAdmin.priority.urgent': 'Urgent',
  'platformAdmin.tier.starter': 'Starter',
  'platformAdmin.tier.growth': 'Growth',
  'platformAdmin.tier.pro': 'Pro',
  'platformAdmin.tier.managed': 'Managed',

  // Workflow board
  'workflow.title': 'Workflow operations',
  'workflow.subtitle': 'Internal operations board for customer & platform tasks.',
  'workflow.security.note':
    'Internal operations only — mock board. No real assignment, notifications, automation execution, or persistence.',
  'workflow.kpi.open': 'Open',
  'workflow.kpi.urgent': 'Urgent',
  'workflow.kpi.overdue': 'Overdue',
  'workflow.kpi.blocked': 'Blocked',
  'workflow.kpi.waitingCustomer': 'Waiting customer',
  'workflow.kpi.doneWeek': 'Done this week',
  'workflow.col.backlog': 'Backlog / To do',
  'workflow.col.inProgress': 'In progress',
  'workflow.col.waitingBlocked': 'Waiting / Blocked',
  'workflow.col.review': 'Review',
  'workflow.col.done': 'Done',
  'workflow.filter.status': 'Status',
  'workflow.filter.priority': 'Priority',
  'workflow.filter.owner': 'Owner',
  'workflow.filter.type': 'Type',
  'workflow.card.next': 'Next',
  'workflow.card.checklist': 'Checklist',
  'workflow.card.due': 'Due',
  'workflow.empty': 'No workflow items match these filters.',
  'workflow.detail.overview': 'Workflow',
  'workflow.detail.relation': 'Customer & site',
  'workflow.detail.checklist': 'Checklist',
  'workflow.detail.timeline': 'Timeline',
  'workflow.detail.signals': 'Related signals',
  'workflow.detail.nextAction': 'Next action',
  'workflow.detail.blocked': 'Blocked reason',
  'workflow.detail.notes': 'Internal notes',
  'workflow.detail.notesPlaceholder': 'Internal notes will live here once the backend lands.',
  'workflow.detail.back': 'Back to board',
  'workflow.detail.owner': 'Owner',
  'workflow.detail.due': 'Due date',
  'workflow.detail.automation': 'Automation readiness (future)',
  'workflow.detail.trigger': 'Trigger',
  'workflow.detail.condition': 'Condition',
  'workflow.detail.action': 'Action',
  'workflow.notFound.title': 'Workflow not found',
  'workflow.notFound.body': 'This workflow item does not exist or is no longer available.',
  'workflow.action.moveInProgress': 'Move to in progress',
  'workflow.action.markReviewed': 'Mark reviewed',
  'workflow.action.assignOwner': 'Assign owner',
  'workflow.action.contactCustomer': 'Contact customer',
  'workflow.action.openSupport': 'Open support case',
  'workflow.action.resolve': 'Resolve',
  'workflow.type.store_launch': 'Store launch',
  'workflow.type.existing_site_connection': 'Site connection',
  'workflow.type.template_setup': 'Template setup',
  'workflow.type.support_handoff': 'Support handoff',
  'workflow.type.plugin_health_issue': 'Plugin health',
  'workflow.type.sync_review': 'Sync review',
  'workflow.type.security_review': 'Security review',
  'workflow.type.billing_followup': 'Billing follow-up',
  'workflow.type.customer_success': 'Customer success',
  'workflow.type.internal_task': 'Internal task',
  'workflow.status.backlog': 'Backlog',
  'workflow.status.todo': 'To do',
  'workflow.status.in_progress': 'In progress',
  'workflow.status.waiting_customer': 'Waiting customer',
  'workflow.status.waiting_internal': 'Waiting internal',
  'workflow.status.blocked': 'Blocked',
  'workflow.status.review': 'Review',
  'workflow.status.done': 'Done',
  'workflow.status.canceled': 'Canceled',
  'workflow.sla.on_track': 'On track',
  'workflow.sla.due_soon': 'Due soon',
  'workflow.sla.overdue': 'Overdue',
  'workflow.sla.paused': 'Paused',
  'workflow.sla.no_sla': 'No SLA',
  'workflow.readiness.manual_only_now': 'Manual only (now)',
  'workflow.readiness.automation_candidate_later': 'Automation candidate (later)',
  'workflow.readiness.requires_backend_later': 'Requires backend (later)',
  'workflow.readiness.requires_provider_later': 'Requires provider (later)',

  // Support inbox
  'nav.support': 'Support',
  'support.title': 'Support inbox',
  'support.subtitle': 'Help SaaS customers with full account context beside each conversation.',
  'support.security.note':
    'Internal support — mock-only. No real chat/email/WhatsApp/phone provider, no message sending, no PII, no secrets. Restricted sections need future RBAC.',
  'support.kpi.open': 'Open',
  'support.kpi.urgent': 'Urgent',
  'support.kpi.overdueSla': 'Overdue SLA',
  'support.kpi.waitingCustomer': 'Waiting customer',
  'support.kpi.unassigned': 'Unassigned',
  'support.kpi.resolvedWeek': 'Resolved this week',
  'support.filter.status': 'Status',
  'support.filter.priority': 'Priority',
  'support.filter.assignee': 'Assignee',
  'support.filter.channel': 'Channel',
  'support.filter.unassigned': 'Unassigned',
  'support.list.unread': 'unread',
  'support.list.updated': 'Updated',
  'support.empty': 'No conversations match these filters.',
  'support.context.title': 'Customer context',
  'support.context.preview': 'Context preview',
  'support.context.selectHint': 'Open a conversation to see full customer context.',
  'support.context.plan': 'Plan & subscription',
  'support.context.owner': 'Support owner',
  'support.context.sites': 'Sites',
  'support.context.siteHealth': 'Active site health',
  'support.context.plugin': 'Plugin',
  'support.context.lastSync': 'Last sync',
  'support.context.signed': 'Signed sync',
  'support.context.queue': 'Event queue',
  'support.context.openWorkflows': 'Open workflow tasks',
  'support.context.openSupport': 'Open support',
  'support.context.usage': 'Usage (API)',
  'support.context.onboarding': 'Onboarding',
  'support.context.onboardingDone': 'Complete',
  'support.context.onboardingPending': 'In progress',
  'support.detail.conversation': 'Conversation',
  'support.detail.messages': 'Messages',
  'support.detail.notes': 'Internal notes',
  'support.detail.notesPlaceholder': 'Internal notes will live here once the backend lands.',
  'support.detail.cannedReplies': 'Canned replies',
  'support.detail.relatedWorkflows': 'Related workflow tasks',
  'support.detail.relatedSignals': 'Related security & audit signals',
  'support.detail.subscription': 'Subscription',
  'support.detail.usage': 'Usage & limits',
  'support.detail.tags': 'Tags',
  'support.detail.back': 'Back to inbox',
  'support.notFound.title': 'Conversation not found',
  'support.notFound.body': 'This conversation does not exist or is no longer available.',
  'support.status.open': 'Open',
  'support.status.pending': 'Pending',
  'support.status.waiting_customer': 'Waiting customer',
  'support.status.waiting_internal': 'Waiting internal',
  'support.status.resolved': 'Resolved',
  'support.status.closed': 'Closed',
  'support.priority.low': 'Low',
  'support.priority.normal': 'Normal',
  'support.priority.high': 'High',
  'support.priority.urgent': 'Urgent',
  'support.sla.on_track': 'On track',
  'support.sla.due_soon': 'Due soon',
  'support.sla.overdue': 'Overdue',
  'support.sla.paused': 'Paused',
  'support.sla.no_sla': 'No SLA',
  'support.channel.chat': 'Chat',
  'support.channel.email': 'Email',
  'support.channel.phone_note': 'Phone note',
  'support.channel.whatsapp_later': 'WhatsApp (later)',
  'support.channel.system_note': 'System note',
  'support.author.customer': 'Customer',
  'support.author.agent': 'Agent',
  'support.author.system': 'System',
  'support.visibility.safe_summary': 'Safe summary',
  'support.visibility.safe_summary.desc': 'Visible to all support agents by default.',
  'support.visibility.support_context': 'Support context',
  'support.visibility.support_context.desc': 'Operational context visible to support agents.',
  'support.visibility.restricted_billing': 'Billing (restricted)',
  'support.visibility.restricted_billing.desc': 'Billing details require billing permission (future RBAC).',
  'support.visibility.restricted_security': 'Security (restricted)',
  'support.visibility.restricted_security.desc': 'Security/audit details require security permission (future RBAC).',
  'support.visibility.never_expose_secret': 'Secrets (never shown)',
  'support.visibility.never_expose_secret.desc': 'Secrets and signing material are never exposed.',
  'support.policy.title': 'Data access policy (future RBAC)',
  'support.policy.safe': 'Support agents see safe summaries by default.',
  'support.policy.billing': 'Billing details require billing permission later.',
  'support.policy.security': 'Security/audit details require security permission later.',
  'support.policy.secrets': 'Secrets and signing material are never shown.',
  'support.policy.pii': 'Raw synced customer PII is not shown.',
  'support.policy.db': 'Direct WordPress database access is forbidden.',
  'support.action.reply': 'Reply',
  'support.action.assign': 'Assign agent',
  'support.action.addNote': 'Add internal note',
  'support.action.resolve': 'Mark resolved',
  'support.action.createWorkflow': 'Create workflow task',
  'support.action.escalate': 'Escalate',
  'support.action.openProfile': 'Open customer profile',
  'support.action.openSiteHealth': 'Open site health',
  'support.openInbox': 'Support inbox',
  'support.history': 'Support history',
  'support.viewConversation': 'View support conversation',
  'health.healthy': 'Healthy',
  'health.degraded': 'Degraded',
  'health.critical': 'Critical',
} as const;

export type LabelKey = keyof typeof en;

export const fa: Record<LabelKey, string> = {
  'app.name': 'مدیریت پلتفرم وردپرس کامرس',
  'app.tagline': 'عملیات داخلی پلتفرم',
  'common.loading': 'در حال بارگذاری…',
  'common.error': 'مشکلی پیش آمد.',
  'common.retry': 'تلاش مجدد',
  'common.back': 'بازگشت',
  'common.mock': 'آزمایشی',
  'common.all': 'همه',
  'common.none': '—',
  'common.localeToggle': 'فا',
  'nav.overview': 'نمای کلی',
  'nav.workflows': 'گردش‌کارها',

  'platformAdmin.title': 'مدیریت پلتفرم',
  'platformAdmin.subtitle': 'مدیریت مشتریان SaaS، فروشگاه‌های آن‌ها و سلامت پلتفرم.',
  'platformAdmin.security.note':
    'لایهٔ کنترل داخلی — فقط آزمایشی. بدون صورتحساب واقعی، سرور، کلید یا اطلاعات شخصی مشتری. پیش از دادهٔ واقعی، RBAC سخت‌گیرانه لازم است.',
  'platformAdmin.kpi.customers': 'مشتریان',
  'platformAdmin.kpi.activeSites': 'سایت‌های فعال',
  'platformAdmin.kpi.mrr': 'درآمد ماهانه (آزمایشی)',
  'platformAdmin.kpi.openSupport': 'پشتیبانی باز',
  'platformAdmin.kpi.syncIssues': 'مشکلات همگام‌سازی',
  'platformAdmin.kpi.securityAlerts': 'هشدارهای امنیتی',
  'platformAdmin.section.atRisk': 'سلامت مشتری',
  'platformAdmin.section.sitesHealth': 'سلامت سایت و همگام‌سازی',
  'platformAdmin.section.subscriptions': 'سلامت اشتراک',
  'platformAdmin.section.support': 'عملیات پشتیبانی',
  'platformAdmin.section.security': 'رویدادهای امنیتی و ممیزی اخیر',
  'platformAdmin.section.usage': 'مصرف و محدودیت‌ها',
  'platformAdmin.section.tasks': 'کارهای بعدی ادمین',
  'platformAdmin.filter.atRisk': 'در معرض ریسک',
  'platformAdmin.filter.pastDue': 'سررسید گذشته',
  'platformAdmin.empty.tenants': 'مشتری‌ای با این فیلتر یافت نشد.',
  'platformAdmin.empty.signals': 'هیچ رویداد امنیتی‌ای وجود ندارد.',
  'platformAdmin.empty.tasks': 'کار بازی برای ادمین وجود ندارد.',
  'platformAdmin.empty.sites': 'سایتی برای نمایش نیست.',
  'platformAdmin.tenant.sitesLabel': 'سایت',
  'platformAdmin.tenant.lastActive': 'آخرین فعالیت',
  'platformAdmin.viewCustomer': 'باز کردن',
  'platformAdmin.owner': 'مالک',
  'platformAdmin.plan': 'پلن',
  'platformAdmin.renews': 'تمدید',
  'platformAdmin.trialEnds': 'پایان دورهٔ آزمایشی',
  'platformAdmin.health': 'سلامت',
  'platformAdmin.mrr': 'درآمد ماهانه (آزمایشی)',
  'platformAdmin.detail.profile': 'مشخصات مشتری',
  'platformAdmin.detail.subscription': 'اشتراک',
  'platformAdmin.detail.sites': 'سایت‌ها و سلامت همگام‌سازی',
  'platformAdmin.detail.tasks': 'کارهای پشتیبانی و ادمین',
  'platformAdmin.detail.security': 'رویدادهای امنیتی و ممیزی',
  'platformAdmin.detail.usage': 'مصرف و محدودیت‌ها',
  'platformAdmin.detail.notes': 'یادداشت‌های داخلی',
  'platformAdmin.detail.notesPlaceholder': 'یادداشت‌های داخلی پس از آماده‌شدن سرور اینجا قرار می‌گیرد.',
  'platformAdmin.detail.back': 'بازگشت به نمای کلی',
  'platformAdmin.notFound.title': 'مشتری یافت نشد',
  'platformAdmin.notFound.body': 'این مشتری/مستأجر وجود ندارد یا دیگر در دسترس نیست.',
  'platformAdmin.action.openSupport': 'ایجاد تیکت پشتیبانی',
  'platformAdmin.action.requestUpgrade': 'درخواست ارتقا',
  'platformAdmin.action.reviewSync': 'بررسی مشکل همگام‌سازی',
  'platformAdmin.action.contactLater': 'تماس با مشتری',
  'platformAdmin.action.suspendLater': 'تعلیق',
  'platformAdmin.site.woo': 'ووکامرس',
  'platformAdmin.site.wooActive': 'ووکامرس فعال',
  'platformAdmin.site.wooMissing': 'ووکامرس غیرفعال',
  'platformAdmin.site.plugin': 'افزونه',
  'platformAdmin.site.lastSync': 'آخرین همگام‌سازی',
  'platformAdmin.site.queued': 'در صف',
  'platformAdmin.site.failures': 'خطاها',
  'platformAdmin.site.signed': 'همگام‌سازی امضاشده',
  'platformAdmin.usage.orders': 'سفارش‌های همگام‌شده',
  'platformAdmin.usage.events': 'رویدادهای ثبت‌شده',
  'platformAdmin.usage.api': 'فراخوانی‌های API',
  'platformAdmin.usage.sites': 'سایت‌ها',
  'platformAdmin.usage.nearLimit': 'نزدیک به سقف',
  'platformAdmin.task.next': 'اقدام بعدی',
  'platformAdmin.task.blocked': 'مسدود',

  'platformAdmin.tenantStatus.active': 'فعال',
  'platformAdmin.tenantStatus.trialing': 'دورهٔ آزمایشی',
  'platformAdmin.tenantStatus.past_due': 'سررسید گذشته',
  'platformAdmin.tenantStatus.canceled': 'لغوشده',
  'platformAdmin.tenantStatus.suspended': 'معلق',
  'platformAdmin.subState.trialing': 'دورهٔ آزمایشی',
  'platformAdmin.subState.active': 'فعال',
  'platformAdmin.subState.past_due': 'سررسید گذشته',
  'platformAdmin.subState.canceled': 'لغوشده',
  'platformAdmin.connection.connected': 'متصل',
  'platformAdmin.connection.pending': 'در انتظار',
  'platformAdmin.connection.disconnected': 'قطع‌شده',
  'platformAdmin.connection.error': 'خطا',
  'platformAdmin.sync.healthy': 'سالم',
  'platformAdmin.sync.delayed': 'با تأخیر',
  'platformAdmin.sync.stalled': 'متوقف',
  'platformAdmin.sync.never': 'هرگز همگام نشده',
  'platformAdmin.signed.verified': 'امضا: تأییدشده',
  'platformAdmin.signed.unsigned': 'امضا: بدون امضا',
  'platformAdmin.signed.invalid': 'امضا: نامعتبر',
  'platformAdmin.signed.disabled': 'امضا: غیرفعال',
  'platformAdmin.severity.info': 'اطلاع',
  'platformAdmin.severity.warning': 'هشدار',
  'platformAdmin.severity.critical': 'بحرانی',
  'platformAdmin.secType.raw_secret_rejected': 'رد کلید خام',
  'platformAdmin.secType.invalid_signature': 'امضای نامعتبر',
  'platformAdmin.secType.replay_rejected': 'رد درخواست تکراری',
  'platformAdmin.secType.permission_denied': 'عدم دسترسی',
  'platformAdmin.secType.sync_validation_failed': 'شکست اعتبارسنجی همگام‌سازی',
  'platformAdmin.secType.webhook_rejected': 'رد وب‌هوک',
  'platformAdmin.secType.audit_event': 'رویداد ممیزی',
  'platformAdmin.priority.low': 'کم',
  'platformAdmin.priority.medium': 'متوسط',
  'platformAdmin.priority.high': 'زیاد',
  'platformAdmin.priority.urgent': 'فوری',
  'platformAdmin.tier.starter': 'استارتر',
  'platformAdmin.tier.growth': 'رشد',
  'platformAdmin.tier.pro': 'حرفه‌ای',
  'platformAdmin.tier.managed': 'مدیریت‌شده',

  'workflow.title': 'عملیات گردش‌کار',
  'workflow.subtitle': 'بورد عملیات داخلی برای کارهای مشتری و پلتفرم.',
  'workflow.security.note':
    'فقط عملیات داخلی — بورد آزمایشی. بدون تخصیص واقعی، اعلان، اجرای اتوماسیون یا ذخیره‌سازی.',
  'workflow.kpi.open': 'باز',
  'workflow.kpi.urgent': 'فوری',
  'workflow.kpi.overdue': 'گذشته از موعد',
  'workflow.kpi.blocked': 'مسدود',
  'workflow.kpi.waitingCustomer': 'در انتظار مشتری',
  'workflow.kpi.doneWeek': 'انجام‌شده این هفته',
  'workflow.col.backlog': 'بک‌لاگ / انجام‌نشده',
  'workflow.col.inProgress': 'در حال انجام',
  'workflow.col.waitingBlocked': 'در انتظار / مسدود',
  'workflow.col.review': 'بازبینی',
  'workflow.col.done': 'انجام‌شده',
  'workflow.filter.status': 'وضعیت',
  'workflow.filter.priority': 'اولویت',
  'workflow.filter.owner': 'مسئول',
  'workflow.filter.type': 'نوع',
  'workflow.card.next': 'بعدی',
  'workflow.card.checklist': 'چک‌لیست',
  'workflow.card.due': 'موعد',
  'workflow.empty': 'موردی با این فیلترها یافت نشد.',
  'workflow.detail.overview': 'گردش‌کار',
  'workflow.detail.relation': 'مشتری و سایت',
  'workflow.detail.checklist': 'چک‌لیست',
  'workflow.detail.timeline': 'زمان‌بندی',
  'workflow.detail.signals': 'رویدادهای مرتبط',
  'workflow.detail.nextAction': 'اقدام بعدی',
  'workflow.detail.blocked': 'دلیل مسدودی',
  'workflow.detail.notes': 'یادداشت‌های داخلی',
  'workflow.detail.notesPlaceholder': 'یادداشت‌های داخلی پس از آماده‌شدن سرور اینجا قرار می‌گیرد.',
  'workflow.detail.back': 'بازگشت به بورد',
  'workflow.detail.owner': 'مسئول',
  'workflow.detail.due': 'تاریخ موعد',
  'workflow.detail.automation': 'آمادگی اتوماسیون (آینده)',
  'workflow.detail.trigger': 'محرک',
  'workflow.detail.condition': 'شرط',
  'workflow.detail.action': 'اقدام',
  'workflow.notFound.title': 'گردش‌کار یافت نشد',
  'workflow.notFound.body': 'این مورد وجود ندارد یا دیگر در دسترس نیست.',
  'workflow.action.moveInProgress': 'انتقال به در حال انجام',
  'workflow.action.markReviewed': 'علامت بازبینی‌شده',
  'workflow.action.assignOwner': 'تعیین مسئول',
  'workflow.action.contactCustomer': 'تماس با مشتری',
  'workflow.action.openSupport': 'ایجاد تیکت پشتیبانی',
  'workflow.action.resolve': 'حل‌وفصل',
  'workflow.type.store_launch': 'راه‌اندازی فروشگاه',
  'workflow.type.existing_site_connection': 'اتصال سایت',
  'workflow.type.template_setup': 'راه‌اندازی قالب',
  'workflow.type.support_handoff': 'تحویل پشتیبانی',
  'workflow.type.plugin_health_issue': 'سلامت افزونه',
  'workflow.type.sync_review': 'بازبینی همگام‌سازی',
  'workflow.type.security_review': 'بازبینی امنیتی',
  'workflow.type.billing_followup': 'پیگیری صورتحساب',
  'workflow.type.customer_success': 'موفقیت مشتری',
  'workflow.type.internal_task': 'کار داخلی',
  'workflow.status.backlog': 'بک‌لاگ',
  'workflow.status.todo': 'انجام‌نشده',
  'workflow.status.in_progress': 'در حال انجام',
  'workflow.status.waiting_customer': 'در انتظار مشتری',
  'workflow.status.waiting_internal': 'در انتظار داخلی',
  'workflow.status.blocked': 'مسدود',
  'workflow.status.review': 'بازبینی',
  'workflow.status.done': 'انجام‌شده',
  'workflow.status.canceled': 'لغوشده',
  'workflow.sla.on_track': 'در مسیر',
  'workflow.sla.due_soon': 'نزدیک موعد',
  'workflow.sla.overdue': 'گذشته از موعد',
  'workflow.sla.paused': 'متوقف',
  'workflow.sla.no_sla': 'بدون SLA',
  'workflow.readiness.manual_only_now': 'فعلاً فقط دستی',
  'workflow.readiness.automation_candidate_later': 'کاندید اتوماسیون (بعداً)',
  'workflow.readiness.requires_backend_later': 'نیازمند سرور (بعداً)',
  'workflow.readiness.requires_provider_later': 'نیازمند ارائه‌دهنده (بعداً)',

  // Support inbox
  'nav.support': 'پشتیبانی',
  'support.title': 'صندوق پشتیبانی',
  'support.subtitle': 'پشتیبانی از مشتریان SaaS همراه با زمینهٔ کامل حساب در کنار هر گفتگو.',
  'support.security.note':
    'پشتیبانی داخلی — فقط آزمایشی. بدون ارائه‌دهندهٔ واقعی چت/ایمیل/واتساپ/تلفن، بدون ارسال پیام، بدون اطلاعات شخصی یا کلید. بخش‌های محدود نیازمند RBAC آینده‌اند.',
  'support.kpi.open': 'باز',
  'support.kpi.urgent': 'فوری',
  'support.kpi.overdueSla': 'SLA گذشته از موعد',
  'support.kpi.waitingCustomer': 'در انتظار مشتری',
  'support.kpi.unassigned': 'تخصیص‌نیافته',
  'support.kpi.resolvedWeek': 'حل‌شده این هفته',
  'support.filter.status': 'وضعیت',
  'support.filter.priority': 'اولویت',
  'support.filter.assignee': 'مسئول',
  'support.filter.channel': 'کانال',
  'support.filter.unassigned': 'تخصیص‌نیافته',
  'support.list.unread': 'خوانده‌نشده',
  'support.list.updated': 'به‌روزرسانی',
  'support.empty': 'گفتگویی با این فیلترها یافت نشد.',
  'support.context.title': 'زمینهٔ مشتری',
  'support.context.preview': 'پیش‌نمایش زمینه',
  'support.context.selectHint': 'برای دیدن زمینهٔ کامل مشتری، یک گفتگو را باز کنید.',
  'support.context.plan': 'پلن و اشتراک',
  'support.context.owner': 'مسئول پشتیبانی',
  'support.context.sites': 'سایت‌ها',
  'support.context.siteHealth': 'سلامت سایت فعال',
  'support.context.plugin': 'افزونه',
  'support.context.lastSync': 'آخرین همگام‌سازی',
  'support.context.signed': 'همگام‌سازی امضاشده',
  'support.context.queue': 'صف رویداد',
  'support.context.openWorkflows': 'کارهای باز گردش‌کار',
  'support.context.openSupport': 'پشتیبانی باز',
  'support.context.usage': 'مصرف (API)',
  'support.context.onboarding': 'راه‌اندازی',
  'support.context.onboardingDone': 'کامل',
  'support.context.onboardingPending': 'در حال انجام',
  'support.detail.conversation': 'گفتگو',
  'support.detail.messages': 'پیام‌ها',
  'support.detail.notes': 'یادداشت‌های داخلی',
  'support.detail.notesPlaceholder': 'یادداشت‌های داخلی پس از آماده‌شدن سرور اینجا قرار می‌گیرد.',
  'support.detail.cannedReplies': 'پاسخ‌های آماده',
  'support.detail.relatedWorkflows': 'کارهای مرتبط گردش‌کار',
  'support.detail.relatedSignals': 'رویدادهای امنیتی و ممیزی مرتبط',
  'support.detail.subscription': 'اشتراک',
  'support.detail.usage': 'مصرف و محدودیت‌ها',
  'support.detail.tags': 'برچسب‌ها',
  'support.detail.back': 'بازگشت به صندوق',
  'support.notFound.title': 'گفتگو یافت نشد',
  'support.notFound.body': 'این گفتگو وجود ندارد یا دیگر در دسترس نیست.',
  'support.status.open': 'باز',
  'support.status.pending': 'در انتظار',
  'support.status.waiting_customer': 'در انتظار مشتری',
  'support.status.waiting_internal': 'در انتظار داخلی',
  'support.status.resolved': 'حل‌شده',
  'support.status.closed': 'بسته',
  'support.priority.low': 'کم',
  'support.priority.normal': 'عادی',
  'support.priority.high': 'زیاد',
  'support.priority.urgent': 'فوری',
  'support.sla.on_track': 'در مسیر',
  'support.sla.due_soon': 'نزدیک موعد',
  'support.sla.overdue': 'گذشته از موعد',
  'support.sla.paused': 'متوقف',
  'support.sla.no_sla': 'بدون SLA',
  'support.channel.chat': 'چت',
  'support.channel.email': 'ایمیل',
  'support.channel.phone_note': 'یادداشت تلفنی',
  'support.channel.whatsapp_later': 'واتساپ (بعداً)',
  'support.channel.system_note': 'یادداشت سیستمی',
  'support.author.customer': 'مشتری',
  'support.author.agent': 'کارشناس',
  'support.author.system': 'سیستم',
  'support.visibility.safe_summary': 'خلاصهٔ ایمن',
  'support.visibility.safe_summary.desc': 'به‌صورت پیش‌فرض برای همهٔ کارشناسان پشتیبانی قابل مشاهده است.',
  'support.visibility.support_context': 'زمینهٔ پشتیبانی',
  'support.visibility.support_context.desc': 'زمینهٔ عملیاتی قابل مشاهده برای کارشناسان پشتیبانی.',
  'support.visibility.restricted_billing': 'صورتحساب (محدود)',
  'support.visibility.restricted_billing.desc': 'جزئیات صورتحساب نیازمند مجوز صورتحساب است (RBAC آینده).',
  'support.visibility.restricted_security': 'امنیت (محدود)',
  'support.visibility.restricted_security.desc': 'جزئیات امنیتی/ممیزی نیازمند مجوز امنیتی است (RBAC آینده).',
  'support.visibility.never_expose_secret': 'کلیدها (هرگز نمایش داده نمی‌شود)',
  'support.visibility.never_expose_secret.desc': 'کلیدها و مواد امضا هرگز نمایش داده نمی‌شوند.',
  'support.policy.title': 'سیاست دسترسی به داده (RBAC آینده)',
  'support.policy.safe': 'کارشناسان پشتیبانی به‌صورت پیش‌فرض خلاصه‌های ایمن را می‌بینند.',
  'support.policy.billing': 'جزئیات صورتحساب بعداً نیازمند مجوز صورتحساب است.',
  'support.policy.security': 'جزئیات امنیتی/ممیزی بعداً نیازمند مجوز امنیتی است.',
  'support.policy.secrets': 'کلیدها و مواد امضا هرگز نمایش داده نمی‌شوند.',
  'support.policy.pii': 'اطلاعات شخصی همگام‌شدهٔ مشتری نمایش داده نمی‌شود.',
  'support.policy.db': 'دسترسی مستقیم به پایگاه‌دادهٔ وردپرس ممنوع است.',
  'support.action.reply': 'پاسخ',
  'support.action.assign': 'تعیین کارشناس',
  'support.action.addNote': 'افزودن یادداشت داخلی',
  'support.action.resolve': 'علامت حل‌شده',
  'support.action.createWorkflow': 'ایجاد کار گردش‌کار',
  'support.action.escalate': 'ارجاع',
  'support.action.openProfile': 'باز کردن پروفایل مشتری',
  'support.action.openSiteHealth': 'باز کردن سلامت سایت',
  'support.openInbox': 'صندوق پشتیبانی',
  'support.history': 'سابقهٔ پشتیبانی',
  'support.viewConversation': 'مشاهدهٔ گفتگوی پشتیبانی',
  'health.healthy': 'سالم',
  'health.degraded': 'نیازمند توجه',
  'health.critical': 'بحرانی',
};

export const labels = { en, fa } as const;
export type Locale = keyof typeof labels;
