/**
 * Admin app labels (en + fa). A compact, self-contained bilingual map — the admin app does
 * not copy the merchant app's large i18n catalog; it ships only the labels it needs.
 * `fa` must contain every `en` key (enforced by the `Record<LabelKey, string>` type).
 */
export const en = {
  'app.name': 'WordPress Commerce OS Admin',
  'app.tagline': 'Internal platform operations',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong.',
  'common.retry': 'Retry',
  'common.back': 'Back',
  'common.mock': 'Mock',
  'common.all': 'All',
  'common.none': '—',
  'common.localeToggle': 'EN',
  'nav.overview': 'Overview',
  'nav.workflows': 'Workflows',

  // Platform overview
  'platformAdmin.title': 'Platform Admin',
  'platformAdmin.subtitle': 'Manage our SaaS customers, their stores, and platform health.',
  'platformAdmin.security.note':
    'Internal control layer — mock-only. No real billing, backend, secrets, or customer PII. Strict RBAC required before real data.',
  'platformAdmin.kpi.customers': 'Customers',
  'platformAdmin.kpi.activeSites': 'Active sites',
  'platformAdmin.kpi.mrr': 'MRR (mock)',
  'platformAdmin.kpi.openSupport': 'Open support',
  'platformAdmin.kpi.syncIssues': 'Sync issues',
  'platformAdmin.kpi.securityAlerts': 'Security alerts',
  'platformAdmin.section.atRisk': 'Customer health',
  'platformAdmin.section.sitesHealth': 'Site & sync health',
  'platformAdmin.section.subscriptions': 'Subscription health',
  'platformAdmin.section.support': 'Support operations',
  'platformAdmin.section.security': 'Recent security & audit',
  'platformAdmin.section.usage': 'Usage & limits',
  'platformAdmin.section.tasks': 'Next admin tasks',
  'platformAdmin.filter.atRisk': 'At risk',
  'platformAdmin.filter.pastDue': 'Past due',
  'platformAdmin.empty.tenants': 'No customers match this filter.',
  'platformAdmin.empty.signals': 'No security signals.',
  'platformAdmin.empty.tasks': 'No open admin tasks.',
  'platformAdmin.empty.sites': 'No sites to show.',
  'platformAdmin.tenant.sitesLabel': 'sites',
  'platformAdmin.tenant.lastActive': 'Last active',
  'platformAdmin.viewCustomer': 'Open',
  'platformAdmin.owner': 'Owner',
  'platformAdmin.plan': 'Plan',
  'platformAdmin.renews': 'Renews',
  'platformAdmin.trialEnds': 'Trial ends',
  'platformAdmin.health': 'Health',
  'platformAdmin.mrr': 'MRR (mock)',
  'platformAdmin.detail.profile': 'Customer profile',
  'platformAdmin.detail.subscription': 'Subscription',
  'platformAdmin.detail.sites': 'Sites & sync health',
  'platformAdmin.detail.tasks': 'Support & admin tasks',
  'platformAdmin.detail.security': 'Security & audit signals',
  'platformAdmin.detail.usage': 'Usage & limits',
  'platformAdmin.detail.notes': 'Internal notes',
  'platformAdmin.detail.notesPlaceholder': 'Internal notes will live here once the backend lands.',
  'platformAdmin.detail.back': 'Back to overview',
  'platformAdmin.notFound.title': 'Customer not found',
  'platformAdmin.notFound.body': 'This customer/tenant does not exist or is no longer available.',
  'platformAdmin.action.openSupport': 'Open support case',
  'platformAdmin.action.requestUpgrade': 'Request upgrade',
  'platformAdmin.action.reviewSync': 'Review sync issue',
  'platformAdmin.action.contactLater': 'Contact customer',
  'platformAdmin.action.suspendLater': 'Suspend',
  'platformAdmin.site.woo': 'WooCommerce',
  'platformAdmin.site.wooActive': 'WooCommerce active',
  'platformAdmin.site.wooMissing': 'WooCommerce missing',
  'platformAdmin.site.plugin': 'Plugin',
  'platformAdmin.site.lastSync': 'Last sync',
  'platformAdmin.site.queued': 'Queued',
  'platformAdmin.site.failures': 'Failures',
  'platformAdmin.site.signed': 'Signed sync',
  'platformAdmin.usage.orders': 'Orders synced',
  'platformAdmin.usage.events': 'Events captured',
  'platformAdmin.usage.api': 'API calls',
  'platformAdmin.usage.sites': 'Sites',
  'platformAdmin.usage.nearLimit': 'Near limit',
  'platformAdmin.task.next': 'Next',
  'platformAdmin.task.blocked': 'Blocked',

  // Status maps
  'platformAdmin.tenantStatus.active': 'Active',
  'platformAdmin.tenantStatus.trialing': 'Trialing',
  'platformAdmin.tenantStatus.past_due': 'Past due',
  'platformAdmin.tenantStatus.canceled': 'Canceled',
  'platformAdmin.tenantStatus.suspended': 'Suspended',
  'platformAdmin.subState.trialing': 'Trialing',
  'platformAdmin.subState.active': 'Active',
  'platformAdmin.subState.past_due': 'Past due',
  'platformAdmin.subState.canceled': 'Canceled',
  'platformAdmin.connection.connected': 'Connected',
  'platformAdmin.connection.pending': 'Pending',
  'platformAdmin.connection.disconnected': 'Disconnected',
  'platformAdmin.connection.error': 'Error',
  'platformAdmin.sync.healthy': 'Healthy',
  'platformAdmin.sync.delayed': 'Delayed',
  'platformAdmin.sync.stalled': 'Stalled',
  'platformAdmin.sync.never': 'Never synced',
  'platformAdmin.signed.verified': 'Signed: verified',
  'platformAdmin.signed.unsigned': 'Signed: unsigned',
  'platformAdmin.signed.invalid': 'Signed: invalid',
  'platformAdmin.signed.disabled': 'Signed: disabled',
  'platformAdmin.severity.info': 'Info',
  'platformAdmin.severity.warning': 'Warning',
  'platformAdmin.severity.critical': 'Critical',
  'platformAdmin.secType.raw_secret_rejected': 'Raw secret rejected',
  'platformAdmin.secType.invalid_signature': 'Invalid signature',
  'platformAdmin.secType.replay_rejected': 'Replay rejected',
  'platformAdmin.secType.permission_denied': 'Permission denied',
  'platformAdmin.secType.sync_validation_failed': 'Sync validation failed',
  'platformAdmin.secType.webhook_rejected': 'Webhook rejected',
  'platformAdmin.secType.audit_event': 'Audit event',
  'platformAdmin.priority.low': 'Low',
  'platformAdmin.priority.medium': 'Medium',
  'platformAdmin.priority.high': 'High',
  'platformAdmin.priority.urgent': 'Urgent',
  'platformAdmin.tier.starter': 'Starter',
  'platformAdmin.tier.growth': 'Growth',
  'platformAdmin.tier.pro': 'Pro',
  'platformAdmin.tier.managed': 'Managed',

  // Workflow board
  'workflow.title': 'Workflow operations',
  'workflow.subtitle': 'Internal operations board for customer & platform tasks.',
  'workflow.security.note':
    'Internal operations only — mock board. No real assignment, notifications, automation execution, or persistence.',
  'workflow.kpi.open': 'Open',
  'workflow.kpi.urgent': 'Urgent',
  'workflow.kpi.overdue': 'Overdue',
  'workflow.kpi.blocked': 'Blocked',
  'workflow.kpi.waitingCustomer': 'Waiting customer',
  'workflow.kpi.doneWeek': 'Done this week',
  'workflow.col.backlog': 'Backlog / To do',
  'workflow.col.inProgress': 'In progress',
  'workflow.col.waitingBlocked': 'Waiting / Blocked',
  'workflow.col.review': 'Review',
  'workflow.col.done': 'Done',
  'workflow.filter.status': 'Status',
  'workflow.filter.priority': 'Priority',
  'workflow.filter.owner': 'Owner',
  'workflow.filter.type': 'Type',
  'workflow.card.next': 'Next',
  'workflow.card.checklist': 'Checklist',
  'workflow.card.due': 'Due',
  'workflow.empty': 'No workflow items match these filters.',
  'workflow.detail.overview': 'Workflow',
  'workflow.detail.relation': 'Customer & site',
  'workflow.detail.checklist': 'Checklist',
  'workflow.detail.timeline': 'Timeline',
  'workflow.detail.signals': 'Related signals',
  'workflow.detail.nextAction': 'Next action',
  'workflow.detail.blocked': 'Blocked reason',
  'workflow.detail.notes': 'Internal notes',
  'workflow.detail.notesPlaceholder': 'Internal notes will live here once the backend lands.',
  'workflow.detail.back': 'Back to board',
  'workflow.detail.owner': 'Owner',
  'workflow.detail.due': 'Due date',
  'workflow.detail.automation': 'Automation readiness (future)',
  'workflow.detail.trigger': 'Trigger',
  'workflow.detail.condition': 'Condition',
  'workflow.detail.action': 'Action',
  'workflow.notFound.title': 'Workflow not found',
  'workflow.notFound.body': 'This workflow item does not exist or is no longer available.',
  'workflow.action.moveInProgress': 'Move to in progress',
  'workflow.action.markReviewed': 'Mark reviewed',
  'workflow.action.assignOwner': 'Assign owner',
  'workflow.action.contactCustomer': 'Contact customer',
  'workflow.action.openSupport': 'Open support case',
  'workflow.action.resolve': 'Resolve',
  'workflow.type.store_launch': 'Store launch',
  'workflow.type.existing_site_connection': 'Site connection',
  'workflow.type.template_setup': 'Template setup',
  'workflow.type.support_handoff': 'Support handoff',
  'workflow.type.plugin_health_issue': 'Plugin health',
  'workflow.type.sync_review': 'Sync review',
  'workflow.type.security_review': 'Security review',
  'workflow.type.billing_followup': 'Billing follow-up',
  'workflow.type.customer_success': 'Customer success',
  'workflow.type.internal_task': 'Internal task',
  'workflow.status.backlog': 'Backlog',
  'workflow.status.todo': 'To do',
  'workflow.status.in_progress': 'In progress',
  'workflow.status.waiting_customer': 'Waiting customer',
  'workflow.status.waiting_internal': 'Waiting internal',
  'workflow.status.blocked': 'Blocked',
  'workflow.status.review': 'Review',
  'workflow.status.done': 'Done',
  'workflow.status.canceled': 'Canceled',
  'workflow.sla.on_track': 'On track',
  'workflow.sla.due_soon': 'Due soon',
  'workflow.sla.overdue': 'Overdue',
  'workflow.sla.paused': 'Paused',
  'workflow.sla.no_sla': 'No SLA',
  'workflow.readiness.manual_only_now': 'Manual only (now)',
  'workflow.readiness.automation_candidate_later': 'Automation candidate (later)',
  'workflow.readiness.requires_backend_later': 'Requires backend (later)',
  'workflow.readiness.requires_provider_later': 'Requires provider (later)',

  'health.healthy': 'Healthy',
  'health.degraded': 'Degraded',
  'health.critical': 'Critical',
} as const;

export type LabelKey = keyof typeof en;

export const fa: Record<LabelKey, string> = {
  'app.name': 'مدیریت پلتفرم وردپرس کامرس',
  'app.tagline': 'عملیات داخلی پلتفرم',
  'common.loading': 'در حال بارگذاری…',
  'common.error': 'مشکلی پیش آمد.',
  'common.retry': 'تلاش مجدد',
  'common.back': 'بازگشت',
  'common.mock': 'آزمایشی',
  'common.all': 'همه',
  'common.none': '—',
  'common.localeToggle': 'فا',
  'nav.overview': 'نمای کلی',
  'nav.workflows': 'گردش‌کارها',

  'platformAdmin.title': 'مدیریت پلتفرم',
  'platformAdmin.subtitle': 'مدیریت مشتریان SaaS، فروشگاه‌های آن‌ها و سلامت پلتفرم.',
  'platformAdmin.security.note':
    'لایهٔ کنترل داخلی — فقط آزمایشی. بدون صورتحساب واقعی، سرور، کلید یا اطلاعات شخصی مشتری. پیش از دادهٔ واقعی، RBAC سخت‌گیرانه لازم است.',
  'platformAdmin.kpi.customers': 'مشتریان',
  'platformAdmin.kpi.activeSites': 'سایت‌های فعال',
  'platformAdmin.kpi.mrr': 'درآمد ماهانه (آزمایشی)',
  'platformAdmin.kpi.openSupport': 'پشتیبانی باز',
  'platformAdmin.kpi.syncIssues': 'مشکلات همگام‌سازی',
  'platformAdmin.kpi.securityAlerts': 'هشدارهای امنیتی',
  'platformAdmin.section.atRisk': 'سلامت مشتری',
  'platformAdmin.section.sitesHealth': 'سلامت سایت و همگام‌سازی',
  'platformAdmin.section.subscriptions': 'سلامت اشتراک',
  'platformAdmin.section.support': 'عملیات پشتیبانی',
  'platformAdmin.section.security': 'رویدادهای امنیتی و ممیزی اخیر',
  'platformAdmin.section.usage': 'مصرف و محدودیت‌ها',
  'platformAdmin.section.tasks': 'کارهای بعدی ادمین',
  'platformAdmin.filter.atRisk': 'در معرض ریسک',
  'platformAdmin.filter.pastDue': 'سررسید گذشته',
  'platformAdmin.empty.tenants': 'مشتری‌ای با این فیلتر یافت نشد.',
  'platformAdmin.empty.signals': 'هیچ رویداد امنیتی‌ای وجود ندارد.',
  'platformAdmin.empty.tasks': 'کار بازی برای ادمین وجود ندارد.',
  'platformAdmin.empty.sites': 'سایتی برای نمایش نیست.',
  'platformAdmin.tenant.sitesLabel': 'سایت',
  'platformAdmin.tenant.lastActive': 'آخرین فعالیت',
  'platformAdmin.viewCustomer': 'باز کردن',
  'platformAdmin.owner': 'مالک',
  'platformAdmin.plan': 'پلن',
  'platformAdmin.renews': 'تمدید',
  'platformAdmin.trialEnds': 'پایان دورهٔ آزمایشی',
  'platformAdmin.health': 'سلامت',
  'platformAdmin.mrr': 'درآمد ماهانه (آزمایشی)',
  'platformAdmin.detail.profile': 'مشخصات مشتری',
  'platformAdmin.detail.subscription': 'اشتراک',
  'platformAdmin.detail.sites': 'سایت‌ها و سلامت همگام‌سازی',
  'platformAdmin.detail.tasks': 'کارهای پشتیبانی و ادمین',
  'platformAdmin.detail.security': 'رویدادهای امنیتی و ممیزی',
  'platformAdmin.detail.usage': 'مصرف و محدودیت‌ها',
  'platformAdmin.detail.notes': 'یادداشت‌های داخلی',
  'platformAdmin.detail.notesPlaceholder': 'یادداشت‌های داخلی پس از آماده‌شدن سرور اینجا قرار می‌گیرد.',
  'platformAdmin.detail.back': 'بازگشت به نمای کلی',
  'platformAdmin.notFound.title': 'مشتری یافت نشد',
  'platformAdmin.notFound.body': 'این مشتری/مستأجر وجود ندارد یا دیگر در دسترس نیست.',
  'platformAdmin.action.openSupport': 'ایجاد تیکت پشتیبانی',
  'platformAdmin.action.requestUpgrade': 'درخواست ارتقا',
  'platformAdmin.action.reviewSync': 'بررسی مشکل همگام‌سازی',
  'platformAdmin.action.contactLater': 'تماس با مشتری',
  'platformAdmin.action.suspendLater': 'تعلیق',
  'platformAdmin.site.woo': 'ووکامرس',
  'platformAdmin.site.wooActive': 'ووکامرس فعال',
  'platformAdmin.site.wooMissing': 'ووکامرس غیرفعال',
  'platformAdmin.site.plugin': 'افزونه',
  'platformAdmin.site.lastSync': 'آخرین همگام‌سازی',
  'platformAdmin.site.queued': 'در صف',
  'platformAdmin.site.failures': 'خطاها',
  'platformAdmin.site.signed': 'همگام‌سازی امضاشده',
  'platformAdmin.usage.orders': 'سفارش‌های همگام‌شده',
  'platformAdmin.usage.events': 'رویدادهای ثبت‌شده',
  'platformAdmin.usage.api': 'فراخوانی‌های API',
  'platformAdmin.usage.sites': 'سایت‌ها',
  'platformAdmin.usage.nearLimit': 'نزدیک به سقف',
  'platformAdmin.task.next': 'اقدام بعدی',
  'platformAdmin.task.blocked': 'مسدود',

  'platformAdmin.tenantStatus.active': 'فعال',
  'platformAdmin.tenantStatus.trialing': 'دورهٔ آزمایشی',
  'platformAdmin.tenantStatus.past_due': 'سررسید گذشته',
  'platformAdmin.tenantStatus.canceled': 'لغوشده',
  'platformAdmin.tenantStatus.suspended': 'معلق',
  'platformAdmin.subState.trialing': 'دورهٔ آزمایشی',
  'platformAdmin.subState.active': 'فعال',
  'platformAdmin.subState.past_due': 'سررسید گذشته',
  'platformAdmin.subState.canceled': 'لغوشده',
  'platformAdmin.connection.connected': 'متصل',
  'platformAdmin.connection.pending': 'در انتظار',
  'platformAdmin.connection.disconnected': 'قطع‌شده',
  'platformAdmin.connection.error': 'خطا',
  'platformAdmin.sync.healthy': 'سالم',
  'platformAdmin.sync.delayed': 'با تأخیر',
  'platformAdmin.sync.stalled': 'متوقف',
  'platformAdmin.sync.never': 'هرگز همگام نشده',
  'platformAdmin.signed.verified': 'امضا: تأییدشده',
  'platformAdmin.signed.unsigned': 'امضا: بدون امضا',
  'platformAdmin.signed.invalid': 'امضا: نامعتبر',
  'platformAdmin.signed.disabled': 'امضا: غیرفعال',
  'platformAdmin.severity.info': 'اطلاع',
  'platformAdmin.severity.warning': 'هشدار',
  'platformAdmin.severity.critical': 'بحرانی',
  'platformAdmin.secType.raw_secret_rejected': 'رد کلید خام',
  'platformAdmin.secType.invalid_signature': 'امضای نامعتبر',
  'platformAdmin.secType.replay_rejected': 'رد درخواست تکراری',
  'platformAdmin.secType.permission_denied': 'عدم دسترسی',
  'platformAdmin.secType.sync_validation_failed': 'شکست اعتبارسنجی همگام‌سازی',
  'platformAdmin.secType.webhook_rejected': 'رد وب‌هوک',
  'platformAdmin.secType.audit_event': 'رویداد ممیزی',
  'platformAdmin.priority.low': 'کم',
  'platformAdmin.priority.medium': 'متوسط',
  'platformAdmin.priority.high': 'زیاد',
  'platformAdmin.priority.urgent': 'فوری',
  'platformAdmin.tier.starter': 'استارتر',
  'platformAdmin.tier.growth': 'رشد',
  'platformAdmin.tier.pro': 'حرفه‌ای',
  'platformAdmin.tier.managed': 'مدیریت‌شده',

  'workflow.title': 'عملیات گردش‌کار',
  'workflow.subtitle': 'بورد عملیات داخلی برای کارهای مشتری و پلتفرم.',
  'workflow.security.note':
    'فقط عملیات داخلی — بورد آزمایشی. بدون تخصیص واقعی، اعلان، اجرای اتوماسیون یا ذخیره‌سازی.',
  'workflow.kpi.open': 'باز',
  'workflow.kpi.urgent': 'فوری',
  'workflow.kpi.overdue': 'گذشته از موعد',
  'workflow.kpi.blocked': 'مسدود',
  'workflow.kpi.waitingCustomer': 'در انتظار مشتری',
  'workflow.kpi.doneWeek': 'انجام‌شده این هفته',
  'workflow.col.backlog': 'بک‌لاگ / انجام‌نشده',
  'workflow.col.inProgress': 'در حال انجام',
  'workflow.col.waitingBlocked': 'در انتظار / مسدود',
  'workflow.col.review': 'بازبینی',
  'workflow.col.done': 'انجام‌شده',
  'workflow.filter.status': 'وضعیت',
  'workflow.filter.priority': 'اولویت',
  'workflow.filter.owner': 'مسئول',
  'workflow.filter.type': 'نوع',
  'workflow.card.next': 'بعدی',
  'workflow.card.checklist': 'چک‌لیست',
  'workflow.card.due': 'موعد',
  'workflow.empty': 'موردی با این فیلترها یافت نشد.',
  'workflow.detail.overview': 'گردش‌کار',
  'workflow.detail.relation': 'مشتری و سایت',
  'workflow.detail.checklist': 'چک‌لیست',
  'workflow.detail.timeline': 'زمان‌بندی',
  'workflow.detail.signals': 'رویدادهای مرتبط',
  'workflow.detail.nextAction': 'اقدام بعدی',
  'workflow.detail.blocked': 'دلیل مسدودی',
  'workflow.detail.notes': 'یادداشت‌های داخلی',
  'workflow.detail.notesPlaceholder': 'یادداشت‌های داخلی پس از آماده‌شدن سرور اینجا قرار می‌گیرد.',
  'workflow.detail.back': 'بازگشت به بورد',
  'workflow.detail.owner': 'مسئول',
  'workflow.detail.due': 'تاریخ موعد',
  'workflow.detail.automation': 'آمادگی اتوماسیون (آینده)',
  'workflow.detail.trigger': 'محرک',
  'workflow.detail.condition': 'شرط',
  'workflow.detail.action': 'اقدام',
  'workflow.notFound.title': 'گردش‌کار یافت نشد',
  'workflow.notFound.body': 'این مورد وجود ندارد یا دیگر در دسترس نیست.',
  'workflow.action.moveInProgress': 'انتقال به در حال انجام',
  'workflow.action.markReviewed': 'علامت بازبینی‌شده',
  'workflow.action.assignOwner': 'تعیین مسئول',
  'workflow.action.contactCustomer': 'تماس با مشتری',
  'workflow.action.openSupport': 'ایجاد تیکت پشتیبانی',
  'workflow.action.resolve': 'حل‌وفصل',
  'workflow.type.store_launch': 'راه‌اندازی فروشگاه',
  'workflow.type.existing_site_connection': 'اتصال سایت',
  'workflow.type.template_setup': 'راه‌اندازی قالب',
  'workflow.type.support_handoff': 'تحویل پشتیبانی',
  'workflow.type.plugin_health_issue': 'سلامت افزونه',
  'workflow.type.sync_review': 'بازبینی همگام‌سازی',
  'workflow.type.security_review': 'بازبینی امنیتی',
  'workflow.type.billing_followup': 'پیگیری صورتحساب',
  'workflow.type.customer_success': 'موفقیت مشتری',
  'workflow.type.internal_task': 'کار داخلی',
  'workflow.status.backlog': 'بک‌لاگ',
  'workflow.status.todo': 'انجام‌نشده',
  'workflow.status.in_progress': 'در حال انجام',
  'workflow.status.waiting_customer': 'در انتظار مشتری',
  'workflow.status.waiting_internal': 'در انتظار داخلی',
  'workflow.status.blocked': 'مسدود',
  'workflow.status.review': 'بازبینی',
  'workflow.status.done': 'انجام‌شده',
  'workflow.status.canceled': 'لغوشده',
  'workflow.sla.on_track': 'در مسیر',
  'workflow.sla.due_soon': 'نزدیک موعد',
  'workflow.sla.overdue': 'گذشته از موعد',
  'workflow.sla.paused': 'متوقف',
  'workflow.sla.no_sla': 'بدون SLA',
  'workflow.readiness.manual_only_now': 'فعلاً فقط دستی',
  'workflow.readiness.automation_candidate_later': 'کاندید اتوماسیون (بعداً)',
  'workflow.readiness.requires_backend_later': 'نیازمند سرور (بعداً)',
  'workflow.readiness.requires_provider_later': 'نیازمند ارائه‌دهنده (بعداً)',

  'health.healthy': 'سالم',
  'health.degraded': 'نیازمند توجه',
  'health.critical': 'بحرانی',
};

export const labels = { en, fa } as const;
export type Locale = keyof typeof labels;
