/**
 * Admin portal mock data (frontend-safe, in-memory, deterministic).
 *
 * Realistic WooCommerce-like platform data for the admin back-office: merchants, platform-wide
 * orders, the marketer network, commission payout requests, and the overview KPIs. No secrets,
 * no card data, no raw PII beyond mock display names. Money values are display-only Persian
 * labels.
 */
import type {
  AdminMarketerSummary,
  AdminMerchant,
  AdminOrderSummary,
  AdminOverview,
  AdminPayoutRequest,
} from '@/domain/admin';

export const ADMIN_MERCHANTS: readonly AdminMerchant[] = [
  {
    id: 'm-1001',
    storeName: 'فروشگاه بادبان',
    ownerName: 'سارا محمدی',
    url: 'badban-shop.example',
    planId: 'growth',
    planName: 'رشد',
    status: 'active',
    mrrLabel: '۴۹۰٬۰۰۰ تومان',
    storeSalesLabel: '۸۲٬۴۰۰٬۰۰۰ تومان',
    ordersCount: 312,
    productsCount: 148,
    joinedAt: '1403-12-02',
    lastActiveAt: '1404-03-28',
    referredByMarketerId: 'mk-01',
    referredByMarketerName: 'رضا کریمی',
  },
  {
    id: 'm-1002',
    storeName: 'دنیای دیجیتال آرین',
    ownerName: 'آرین رستمی',
    url: 'arian-digital.example',
    planId: 'pro',
    planName: 'حرفه‌ای',
    status: 'active',
    mrrLabel: '۹۹۰٬۰۰۰ تومان',
    storeSalesLabel: '۲۴۱٬۰۰۰٬۰۰۰ تومان',
    ordersCount: 1024,
    productsCount: 512,
    joinedAt: '1403-09-14',
    lastActiveAt: '1404-03-29',
    referredByMarketerId: 'mk-02',
    referredByMarketerName: 'نگار احمدی',
  },
  {
    id: 'm-1003',
    storeName: 'بوتیک گل‌سرخ',
    ownerName: 'مریم حسینی',
    url: 'golesorkh.example',
    planId: 'starter',
    planName: 'پایه',
    status: 'trial',
    mrrLabel: 'رایگان (آزمایشی)',
    storeSalesLabel: '۱۲٬۳۰۰٬۰۰۰ تومان',
    ordersCount: 41,
    productsCount: 36,
    joinedAt: '1404-03-10',
    lastActiveAt: '1404-03-27',
  },
  {
    id: 'm-1004',
    storeName: 'لوازم خانگی مهر',
    ownerName: 'حمید عباسی',
    url: 'mehr-home.example',
    planId: 'growth',
    planName: 'رشد',
    status: 'past_due',
    mrrLabel: '۴۹۰٬۰۰۰ تومان',
    storeSalesLabel: '۵۶٬۹۰۰٬۰۰۰ تومان',
    ordersCount: 208,
    productsCount: 97,
    joinedAt: '1403-11-21',
    lastActiveAt: '1404-03-20',
    referredByMarketerId: 'mk-01',
    referredByMarketerName: 'رضا کریمی',
  },
  {
    id: 'm-1005',
    storeName: 'کافه‌کتاب نون',
    ownerName: 'پویا نادری',
    url: 'noon-books.example',
    planId: 'managed',
    planName: 'مدیریت‌شده',
    status: 'active',
    mrrLabel: '۲٬۴۰۰٬۰۰۰ تومان',
    storeSalesLabel: '۱۹۸٬۲۰۰٬۰۰۰ تومان',
    ordersCount: 766,
    productsCount: 240,
    joinedAt: '1403-07-03',
    lastActiveAt: '1404-03-29',
  },
  {
    id: 'm-1006',
    storeName: 'پوشاک ترمه',
    ownerName: 'الهام صادقی',
    url: 'termeh-wear.example',
    planId: 'starter',
    planName: 'پایه',
    status: 'suspended',
    mrrLabel: '۲۴۰٬۰۰۰ تومان',
    storeSalesLabel: '۰ تومان',
    ordersCount: 19,
    productsCount: 22,
    joinedAt: '1404-01-18',
    lastActiveAt: '1404-02-30',
    referredByMarketerId: 'mk-03',
    referredByMarketerName: 'سینا یوسفی',
  },
];

export const ADMIN_ORDERS: readonly AdminOrderSummary[] = [
  {
    id: 'o-9001',
    number: '#10421',
    storeName: 'دنیای دیجیتال آرین',
    merchantId: 'm-1002',
    customerName: 'کیان مرادی',
    status: 'processing',
    totalLabel: '۳٬۸۵۰٬۰۰۰ تومان',
    createdAt: '1404-03-29',
  },
  {
    id: 'o-9002',
    number: '#10420',
    storeName: 'فروشگاه بادبان',
    merchantId: 'm-1001',
    customerName: 'نیلوفر کاظمی',
    status: 'completed',
    totalLabel: '۹۲۰٬۰۰۰ تومان',
    createdAt: '1404-03-29',
  },
  {
    id: 'o-9003',
    number: '#10419',
    storeName: 'کافه‌کتاب نون',
    merchantId: 'm-1005',
    customerName: 'بهرام شریفی',
    status: 'pending',
    totalLabel: '۴۵۰٬۰۰۰ تومان',
    createdAt: '1404-03-28',
  },
  {
    id: 'o-9004',
    number: '#10418',
    storeName: 'لوازم خانگی مهر',
    merchantId: 'm-1004',
    customerName: 'شیرین جعفری',
    status: 'on-hold',
    totalLabel: '۶٬۲۰۰٬۰۰۰ تومان',
    createdAt: '1404-03-28',
  },
  {
    id: 'o-9005',
    number: '#10417',
    storeName: 'دنیای دیجیتال آرین',
    merchantId: 'm-1002',
    customerName: 'آرش تهرانی',
    status: 'refunded',
    totalLabel: '۱٬۱۰۰٬۰۰۰ تومان',
    createdAt: '1404-03-27',
  },
  {
    id: 'o-9006',
    number: '#10416',
    storeName: 'بوتیک گل‌سرخ',
    merchantId: 'm-1003',
    customerName: 'مهسا رحیمی',
    status: 'completed',
    totalLabel: '۷۸۰٬۰۰۰ تومان',
    createdAt: '1404-03-27',
  },
  {
    id: 'o-9007',
    number: '#10415',
    storeName: 'فروشگاه بادبان',
    merchantId: 'm-1001',
    customerName: 'فرهاد قاسمی',
    status: 'cancelled',
    totalLabel: '۳۲۰٬۰۰۰ تومان',
    createdAt: '1404-03-26',
  },
];

export const ADMIN_MARKETERS: readonly AdminMarketerSummary[] = [
  {
    id: 'mk-01',
    name: 'رضا کریمی',
    code: 'REZA20',
    status: 'active',
    referralsTotal: 18,
    activeReferrals: 12,
    commissionRateLabel: '۲۰٪',
    commissionPendingLabel: '۴٬۳۰۰٬۰۰۰ تومان',
    commissionPaidLabel: '۲۸٬۹۰۰٬۰۰۰ تومان',
    joinedAt: '1403-08-12',
  },
  {
    id: 'mk-02',
    name: 'نگار احمدی',
    code: 'NEGAR15',
    status: 'active',
    referralsTotal: 26,
    activeReferrals: 19,
    commissionRateLabel: '۲۵٪',
    commissionPendingLabel: '۷٬۸۰۰٬۰۰۰ تومان',
    commissionPaidLabel: '۵۱٬۲۰۰٬۰۰۰ تومان',
    joinedAt: '1403-06-01',
  },
  {
    id: 'mk-03',
    name: 'سینا یوسفی',
    code: 'SINA10',
    status: 'paused',
    referralsTotal: 7,
    activeReferrals: 3,
    commissionRateLabel: '۱۵٪',
    commissionPendingLabel: '۹۰۰٬۰۰۰ تومان',
    commissionPaidLabel: '۶٬۴۰۰٬۰۰۰ تومان',
    joinedAt: '1404-01-09',
  },
];

export const ADMIN_PAYOUT_REQUESTS: readonly AdminPayoutRequest[] = [
  {
    id: 'po-501',
    marketerId: 'mk-02',
    marketerName: 'نگار احمدی',
    amountLabel: '۷٬۸۰۰٬۰۰۰ تومان',
    method: 'bank_card',
    maskedDestination: 'کارت •••• ۴۳۲۱',
    status: 'requested',
    requestedAt: '1404-03-28',
  },
  {
    id: 'po-502',
    marketerId: 'mk-01',
    marketerName: 'رضا کریمی',
    amountLabel: '۴٬۳۰۰٬۰۰۰ تومان',
    method: 'bank_iban',
    maskedDestination: 'شبا •••• ۹۸۷۶',
    status: 'approved',
    requestedAt: '1404-03-26',
  },
  {
    id: 'po-503',
    marketerId: 'mk-03',
    marketerName: 'سینا یوسفی',
    amountLabel: '۹۰۰٬۰۰۰ تومان',
    method: 'wallet',
    maskedDestination: 'کیف پول •••• ۱۲۳۴',
    status: 'requested',
    requestedAt: '1404-03-25',
  },
];

export const ADMIN_OVERVIEW: AdminOverview = {
  merchantsTotal: ADMIN_MERCHANTS.length,
  merchantsActive: ADMIN_MERCHANTS.filter((m) => m.status === 'active').length,
  merchantsTrialing: ADMIN_MERCHANTS.filter((m) => m.status === 'trial').length,
  mrrLabel: '۱۸٬۲۰۰٬۰۰۰ تومان',
  gmvLabel: '۶۲۹٬۰۰۰٬۰۰۰ تومان',
  openSupport: 5,
  pendingPayouts: ADMIN_PAYOUT_REQUESTS.filter((p) => p.status === 'requested').length,
  pendingPayoutsAmountLabel: '۸٬۷۰۰٬۰۰۰ تومان',
  metrics: [
    { id: 'mrr', label: 'درآمد ماهانه (MRR)', value: '۱۸٫۲M تومان', changeLabel: '+۸٪', tone: 'success' },
    { id: 'gmv', label: 'فروش کل فروشگاه‌ها', value: '۶۲۹M تومان', changeLabel: '+۱۲٪', tone: 'success' },
    { id: 'merchants', label: 'فروشندگان فعال', value: '۳ از ۶', tone: 'info' },
    { id: 'support', label: 'پشتیبانی باز', value: '۵', tone: 'warning' },
  ],
  recentActivity: [
    { id: 'a1', kind: 'merchant', message: 'فروشگاه «بوتیک گل‌سرخ» دوره آزمایشی را شروع کرد.', date: '1404-03-29' },
    { id: 'a2', kind: 'payout', message: 'درخواست تسویه ۷٫۸M تومان از نگار احمدی ثبت شد.', date: '1404-03-28' },
    { id: 'a3', kind: 'order', message: 'سفارش #10421 در «دنیای دیجیتال آرین» در حال پردازش است.', date: '1404-03-29' },
    { id: 'a4', kind: 'marketer', message: 'بازاریاب رضا کریمی یک فروشنده جدید معرفی کرد.', date: '1404-03-27' },
    { id: 'a5', kind: 'support', message: '۲ تیکت پشتیبانی جدید در صف بررسی است.', date: '1404-03-27' },
  ],
};

/** Look up a single merchant by id (frontend-safe). */
export function findAdminMerchant(id: string): AdminMerchant | undefined {
  return ADMIN_MERCHANTS.find((m) => m.id === id);
}
