// Service layer barrel. Screens/hooks import services from here; never adapters directly.
export { authService } from './authService';
export { siteService } from './siteService';
export { dashboardService } from './dashboardService';
export { productService } from './productService';
export { orderService } from './orderService';
export { customerService } from './customerService';
export { onboardingService } from './onboardingService';
export { supportService } from './supportService';
export { subscriptionService } from './subscriptionService';
export type { SubscriptionOverview } from './subscriptionService';
export { aiAdvisorService } from './aiAdvisorService';
export type { AdvisorOverview } from './aiAdvisorService';
export { mediaStudioService } from './mediaStudioService';
export type { MediaStudioInfo } from './mediaStudioService';
export { customerIntelligenceService } from './customerIntelligenceService';
export type { IntelligenceOverview } from './customerIntelligenceService';
export { notificationAutomationService } from './notificationAutomationService';
export type { AutomationOverview } from './notificationAutomationService';
export { reportsAnalyticsService } from './reportsAnalyticsService';
export type { ReportsOverview } from './reportsAnalyticsService';
export { platformAdminService } from './platformAdminService';
export { queryKeys } from './queryKeys';
